New metadata for publishing on App Store
vtex-apps/iubenda pull request #8
Opened 2020-08-20 15:45 UTC by manoel-gumes

What problem is this solving?

Estrutura de pastas (public/metadata) para o novo formato aceito pela App Store.
-> Nesta fase de transição, teremos as duas estruturas de pastas coexistindo.

Adição do arquivo crowdin.yml para localização.

How should this be manually tested?

As mudificações não alteram o comportamento do App.

2020-08-20 17:59 UTC, marlonguimaraes approved these changes
Don't forget to answer bot's questions (version and documentation)

2020-09-15 17:15 UTC, klzns requested changes

2020-09-15 17:15 UTC, klzns commented on crowdin.yml
> +    source: "iubenda/public/metadata/messages/pt-BR.json"
Remove iubenda

2020-09-15 19:52 UTC, marlonguimaraes approved these changes

2020-09-15 19:56 UTC, klzns approved these changes

2020-09-15 20:32 UTC, merged